/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examenlab2_eliasgiron;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EliasGZ
 */
public class Examen2 extends javax.swing.JFrame {

    /**
     * Creates new form Examen2
     */
    public Examen2() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_agregarcom = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_serie = new javax.swing.JTextField();
        tf_ano = new javax.swing.JTextField();
        tf_colorcomp = new javax.swing.JTextField();
        tf_materialcomp = new javax.swing.JTextField();
        jb_ram = new javax.swing.JButton();
        jb_hdd = new javax.swing.JButton();
        jb_bateria = new javax.swing.JButton();
        jb_teclado = new javax.swing.JButton();
        jb_pantalla = new javax.swing.JButton();
        jb_procesador = new javax.swing.JButton();
        jb_agregarcomp = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jb_agregartec = new javax.swing.JButton();
        jd_agregartec = new javax.swing.JDialog();
        jLabel29 = new javax.swing.JLabel();
        tf_nombretec = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        tf_edadtec = new javax.swing.JTextField();
        jb_agregartecnico = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        tf_genero = new javax.swing.JTextField();
        jd_simulacion = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_aensamblar = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_parte = new javax.swing.JTable();
        pgb_ensamblaje = new javax.swing.JProgressBar();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_computadoras = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_tecnicos = new javax.swing.JList<>();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jb_ejecutar = new javax.swing.JButton();
        jd_ram = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        tf_tamano = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tf_marca = new javax.swing.JTextField();
        jb_agregarram = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        tf_ensamblaje1 = new javax.swing.JTextField();
        jd_hdd = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        tf_tamano1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tf_marca1 = new javax.swing.JTextField();
        jb_agregarrom = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        tf_ensamblaje2 = new javax.swing.JTextField();
        jd_bateria = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        tf_horas = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tf_material = new javax.swing.JTextField();
        jb_agregarbat = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        tf_ensamblaje3 = new javax.swing.JTextField();
        jd_teclado = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        tf_materialtec = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tf_colortec = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tf_ensamblaje4 = new javax.swing.JTextField();
        jb_agregarteclado = new javax.swing.JButton();
        jd_pantalla = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        tf_tactil = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tf_tipo = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tf_ensamblaje5 = new javax.swing.JTextField();
        jb_agregarpant = new javax.swing.JButton();
        jd_procesador = new javax.swing.JDialog();
        jLabel26 = new javax.swing.JLabel();
        tf_nucleos = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tf_velocidad = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        tf_ensamblaje6 = new javax.swing.JTextField();
        jb_agregarproc = new javax.swing.JButton();
        popup_acciones = new javax.swing.JPopupMenu();
        jmi_modificar = new javax.swing.JMenuItem();
        jmi_eliminar = new javax.swing.JMenuItem();
        jd_reporte = new javax.swing.JDialog();
        jd_listacomputadoras = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        jl_archivoscomps = new javax.swing.JList<>();
        jb_cargar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jb_ensamblaje = new javax.swing.JButton();
        jb_agregarnueva = new javax.swing.JButton();
        jb_compusensambladas = new javax.swing.JButton();

        jLabel1.setText("Numero de Serie");

        jLabel2.setText("Ano");

        jLabel3.setText("Color");

        jLabel4.setText("Material");

        jLabel5.setText("RAM");

        jLabel6.setText("Disco Duro");

        jLabel7.setText("Bateria");

        jLabel8.setText("Teclado");

        jLabel9.setText("Pantalla");

        jLabel10.setText("Procesador");

        jb_ram.setText("Agregar RAM");
        jb_ram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ramMouseClicked(evt);
            }
        });

        jb_hdd.setText("Agregar Discoduro");
        jb_hdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_hddMouseClicked(evt);
            }
        });

        jb_bateria.setText("Agregar Bateria");
        jb_bateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_bateriaMouseClicked(evt);
            }
        });

        jb_teclado.setText("Agregar Teclado");
        jb_teclado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_tecladoMouseClicked(evt);
            }
        });

        jb_pantalla.setText("Agregar Pantalla");
        jb_pantalla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_pantallaMouseClicked(evt);
            }
        });

        jb_procesador.setText("Agregar Procesador");
        jb_procesador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_procesadorMouseClicked(evt);
            }
        });

        jb_agregarcomp.setText("Agregar Ensamblaje");
        jb_agregarcomp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarcompMouseClicked(evt);
            }
        });

        jLabel33.setText("Agregar Tecnico");

        jb_agregartec.setText("Agregar Tecnico");
        jb_agregartec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregartecMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(tf_serie, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(tf_colorcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_materialcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jb_ram)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(26, 26, 26)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(jb_hdd))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jb_bateria))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(66, 66, 66)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jb_pantalla)
                                    .addComponent(jb_teclado)
                                    .addComponent(jb_procesador))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(93, 93, 93)
                        .addComponent(tf_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(197, 197, 197))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jb_agregarcomp)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel33)
                                    .addGap(18, 18, 18)
                                    .addComponent(jb_agregartec))
                                .addComponent(jLabel10)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(tf_serie, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_colorcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_materialcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jb_ram))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jb_hdd))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jb_bateria))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jb_teclado))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jb_pantalla))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jb_procesador))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jb_agregartec))
                .addGap(43, 43, 43)
                .addComponent(jb_agregarcomp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_agregarcomLayout = new javax.swing.GroupLayout(jd_agregarcom.getContentPane());
        jd_agregarcom.getContentPane().setLayout(jd_agregarcomLayout);
        jd_agregarcomLayout.setHorizontalGroup(
            jd_agregarcomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_agregarcomLayout.setVerticalGroup(
            jd_agregarcomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel29.setText("Nombre");

        jLabel30.setText("Edad");

        jb_agregartecnico.setText("Agregar Tecnico");
        jb_agregartecnico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregartecnicoMouseClicked(evt);
            }
        });

        jLabel32.setText("Genero");

        javax.swing.GroupLayout jd_agregartecLayout = new javax.swing.GroupLayout(jd_agregartec.getContentPane());
        jd_agregartec.getContentPane().setLayout(jd_agregartecLayout);
        jd_agregartecLayout.setHorizontalGroup(
            jd_agregartecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregartecLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jd_agregartecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_agregartecnico)
                    .addGroup(jd_agregartecLayout.createSequentialGroup()
                        .addGroup(jd_agregartecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel29)
                            .addComponent(jLabel32))
                        .addGap(18, 18, 18)
                        .addGroup(jd_agregartecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombretec, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(tf_edadtec)
                            .addComponent(tf_genero))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jd_agregartecLayout.setVerticalGroup(
            jd_agregartecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregartecLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jd_agregartecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(tf_nombretec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_agregartecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(tf_edadtec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_agregartecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(tf_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jb_agregartecnico)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jl_aensamblar.setModel(new DefaultListModel());
        jl_aensamblar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_aensamblarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_aensamblar);

        jt_parte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pieza"
            }
        ));
        jScrollPane2.setViewportView(jt_parte);

        jLabel31.setText("Ensamblaje");

        jl_computadoras.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_computadoras);

        jl_tecnicos.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(jl_tecnicos);

        jLabel34.setText("Computadoras");

        jLabel35.setText("Tecnicos");

        jb_ejecutar.setText("Ejecutar Ensamble");
        jb_ejecutar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ejecutarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_simulacionLayout = new javax.swing.GroupLayout(jd_simulacion.getContentPane());
        jd_simulacion.getContentPane().setLayout(jd_simulacionLayout);
        jd_simulacionLayout.setHorizontalGroup(
            jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_simulacionLayout.createSequentialGroup()
                .addGroup(jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_simulacionLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel31))
                    .addGroup(jd_simulacionLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_simulacionLayout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_simulacionLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_simulacionLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jd_simulacionLayout.createSequentialGroup()
                                        .addGap(140, 140, 140)
                                        .addComponent(jb_ejecutar)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jd_simulacionLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(pgb_ensamblaje, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(jd_simulacionLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel35)
                .addGap(210, 210, 210))
        );
        jd_simulacionLayout.setVerticalGroup(
            jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_simulacionLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_simulacionLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(pgb_ensamblaje, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_simulacionLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jb_ejecutar)))
                .addGap(47, 47, 47))
        );

        jLabel11.setText("Tamano");

        jLabel12.setText("Marca");

        jb_agregarram.setText("Agregar RAM");
        jb_agregarram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarramMouseClicked(evt);
            }
        });

        jLabel18.setText("Tiempo Ensamblaje");

        javax.swing.GroupLayout jd_ramLayout = new javax.swing.GroupLayout(jd_ram.getContentPane());
        jd_ram.getContentPane().setLayout(jd_ramLayout);
        jd_ramLayout.setHorizontalGroup(
            jd_ramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ramLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jd_ramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_agregarram)
                    .addGroup(jd_ramLayout.createSequentialGroup()
                        .addGroup(jd_ramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jd_ramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_tamano, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(tf_marca)
                            .addComponent(tf_ensamblaje1))))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jd_ramLayout.setVerticalGroup(
            jd_ramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ramLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jd_ramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_tamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_ramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jd_ramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_ensamblaje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addComponent(jb_agregarram)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jLabel13.setText("Tamano");

        jLabel14.setText("Marca");

        jb_agregarrom.setText("Agregar ROM");
        jb_agregarrom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarromMouseClicked(evt);
            }
        });

        jLabel19.setText("Tiempo Ensamblaje");

        javax.swing.GroupLayout jd_hddLayout = new javax.swing.GroupLayout(jd_hdd.getContentPane());
        jd_hdd.getContentPane().setLayout(jd_hddLayout);
        jd_hddLayout.setHorizontalGroup(
            jd_hddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_hddLayout.createSequentialGroup()
                .addGroup(jd_hddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_hddLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jb_agregarrom))
                    .addGroup(jd_hddLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jd_hddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jd_hddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_tamano1)
                            .addComponent(tf_marca1)
                            .addComponent(tf_ensamblaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jd_hddLayout.setVerticalGroup(
            jd_hddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_hddLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jd_hddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_tamano1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_hddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_marca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_hddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_ensamblaje2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(28, 28, 28)
                .addComponent(jb_agregarrom)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jLabel15.setText("Capacidad Horas");

        jLabel16.setText("Material");

        jb_agregarbat.setText("Agregar Bateria");
        jb_agregarbat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarbatMouseClicked(evt);
            }
        });

        jLabel17.setText("Tiempo Ensamblaje");

        javax.swing.GroupLayout jd_bateriaLayout = new javax.swing.GroupLayout(jd_bateria.getContentPane());
        jd_bateria.getContentPane().setLayout(jd_bateriaLayout);
        jd_bateriaLayout.setHorizontalGroup(
            jd_bateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_bateriaLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jd_bateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_bateriaLayout.createSequentialGroup()
                        .addGroup(jd_bateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jd_bateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_horas, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(tf_material)
                            .addComponent(tf_ensamblaje3)))
                    .addGroup(jd_bateriaLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jb_agregarbat)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jd_bateriaLayout.setVerticalGroup(
            jd_bateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_bateriaLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jd_bateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_horas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_bateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_bateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_ensamblaje3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jb_agregarbat)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jLabel20.setText("Material");

        jLabel21.setText("Color");

        jLabel22.setText("Tiempo Ensamblaje");

        jb_agregarteclado.setText("Agregar Teclado");
        jb_agregarteclado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregartecladoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_tecladoLayout = new javax.swing.GroupLayout(jd_teclado.getContentPane());
        jd_teclado.getContentPane().setLayout(jd_tecladoLayout);
        jd_tecladoLayout.setHorizontalGroup(
            jd_tecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_tecladoLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jd_tecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_tecladoLayout.createSequentialGroup()
                        .addGroup(jd_tecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(jd_tecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_materialtec, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(tf_colortec)
                            .addComponent(tf_ensamblaje4)))
                    .addGroup(jd_tecladoLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jb_agregarteclado)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jd_tecladoLayout.setVerticalGroup(
            jd_tecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_tecladoLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jd_tecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_materialtec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_tecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tf_colortec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_tecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tf_ensamblaje4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jb_agregarteclado)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jLabel23.setText("Tactil");

        jLabel24.setText("Tipo");

        jLabel25.setText("Tiempo Ensamblaje");

        jb_agregarpant.setText("Agregar Pantalla");
        jb_agregarpant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarpantMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_pantallaLayout = new javax.swing.GroupLayout(jd_pantalla.getContentPane());
        jd_pantalla.getContentPane().setLayout(jd_pantallaLayout);
        jd_pantallaLayout.setHorizontalGroup(
            jd_pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_pantallaLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jd_pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_pantallaLayout.createSequentialGroup()
                        .addGroup(jd_pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addGroup(jd_pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_tactil)
                            .addComponent(tf_tipo)
                            .addComponent(tf_ensamblaje5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_pantallaLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jb_agregarpant)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jd_pantallaLayout.setVerticalGroup(
            jd_pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_pantallaLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jd_pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tf_tactil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(tf_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(tf_ensamblaje5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jb_agregarpant)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jLabel26.setText("Nucleos");

        jLabel27.setText("Velocidad");

        jLabel28.setText("Tiempo Ensamblaje");

        jb_agregarproc.setText("Agregar Teclado");
        jb_agregarproc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarprocMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_procesadorLayout = new javax.swing.GroupLayout(jd_procesador.getContentPane());
        jd_procesador.getContentPane().setLayout(jd_procesadorLayout);
        jd_procesadorLayout.setHorizontalGroup(
            jd_procesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_procesadorLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jd_procesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_procesadorLayout.createSequentialGroup()
                        .addGroup(jd_procesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26)
                            .addComponent(jLabel28))
                        .addGap(18, 18, 18)
                        .addGroup(jd_procesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nucleos)
                            .addComponent(tf_velocidad)
                            .addComponent(tf_ensamblaje6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_procesadorLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jb_agregarproc)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jd_procesadorLayout.setVerticalGroup(
            jd_procesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_procesadorLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jd_procesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tf_nucleos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_procesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(tf_velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_procesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(tf_ensamblaje6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jb_agregarproc)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jmi_modificar.setText("jMenuItem1");
        popup_acciones.add(jmi_modificar);

        jmi_eliminar.setText("jMenuItem2");
        popup_acciones.add(jmi_eliminar);

        javax.swing.GroupLayout jd_reporteLayout = new javax.swing.GroupLayout(jd_reporte.getContentPane());
        jd_reporte.getContentPane().setLayout(jd_reporteLayout);
        jd_reporteLayout.setHorizontalGroup(
            jd_reporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_reporteLayout.setVerticalGroup(
            jd_reporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jl_archivoscomps.setModel(new DefaultListModel());
        jScrollPane5.setViewportView(jl_archivoscomps);

        jb_cargar.setText("Cargar Archivo");
        jb_cargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_cargarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_listacomputadorasLayout = new javax.swing.GroupLayout(jd_listacomputadoras.getContentPane());
        jd_listacomputadoras.getContentPane().setLayout(jd_listacomputadorasLayout);
        jd_listacomputadorasLayout.setHorizontalGroup(
            jd_listacomputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listacomputadorasLayout.createSequentialGroup()
                .addGroup(jd_listacomputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_listacomputadorasLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_listacomputadorasLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jb_cargar)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jd_listacomputadorasLayout.setVerticalGroup(
            jd_listacomputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listacomputadorasLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jb_cargar)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jb_ensamblaje.setText("Ensamblaje");
        jb_ensamblaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ensamblajeMouseClicked(evt);
            }
        });

        jb_agregarnueva.setText("Agregar Ensamblaje");
        jb_agregarnueva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarnuevaMouseClicked(evt);
            }
        });
        jb_agregarnueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agregarnuevaActionPerformed(evt);
            }
        });

        jb_compusensambladas.setText("Ver Computadoras Ensambladas");
        jb_compusensambladas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_compusensambladasMouseClicked(evt);
            }
        });
        jb_compusensambladas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_compusensambladasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jb_compusensambladas)
                .addGap(64, 64, 64))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_ensamblaje, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_agregarnueva))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jb_agregarnueva)
                .addGap(18, 18, 18)
                .addComponent(jb_ensamblaje)
                .addGap(18, 18, 18)
                .addComponent(jb_compusensambladas)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_ensamblajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ensamblajeMouseClicked
        jd_simulacion.setModal(true);
        jd_simulacion.pack();
        jd_simulacion.setLocationRelativeTo(this);
        jd_simulacion.setVisible(true);
    }//GEN-LAST:event_jb_ensamblajeMouseClicked

    private void jb_ramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ramMouseClicked
        jd_ram.setModal(true);
        jd_ram.pack();
        jd_ram.setLocationRelativeTo(this);
        jd_ram.setVisible(true);
    }//GEN-LAST:event_jb_ramMouseClicked

    private void jb_hddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_hddMouseClicked
        jd_hdd.setModal(true);
        jd_hdd.pack();
        jd_hdd.setLocationRelativeTo(this);
        jd_hdd.setVisible(true);
    }//GEN-LAST:event_jb_hddMouseClicked

    private void jb_bateriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_bateriaMouseClicked
        jd_bateria.setModal(true);
        jd_bateria.pack();
        jd_bateria.setLocationRelativeTo(this);
        jd_bateria.setVisible(true);
    }//GEN-LAST:event_jb_bateriaMouseClicked

    private void jb_tecladoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_tecladoMouseClicked
        jd_teclado.setModal(true);
        jd_teclado.pack();
        jd_teclado.setLocationRelativeTo(this);
        jd_teclado.setVisible(true);
    }//GEN-LAST:event_jb_tecladoMouseClicked

    private void jb_pantallaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_pantallaMouseClicked
        jd_pantalla.setModal(true);
        jd_pantalla.pack();
        jd_pantalla.setLocationRelativeTo(this);
        jd_pantalla.setVisible(true);
    }//GEN-LAST:event_jb_pantallaMouseClicked

    private void jb_procesadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_procesadorMouseClicked
        jd_procesador.setModal(true);
        jd_procesador.pack();
        jd_procesador.setLocationRelativeTo(this);
        jd_procesador.setVisible(true);
    }//GEN-LAST:event_jb_procesadorMouseClicked

    private void jb_agregarnuevaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarnuevaMouseClicked
        jd_agregarcom.setModal(true);
        jd_agregarcom.pack();
        jd_agregarcom.setLocationRelativeTo(this);
        jd_agregarcom.setVisible(true);
    }//GEN-LAST:event_jb_agregarnuevaMouseClicked

    private void jb_agregarcompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarcompMouseClicked
        RAM r = new RAM(Integer.parseInt(tf_tamano.getText()), tf_marca.getText(), Integer.parseInt(tf_ensamblaje1.getText()));
        DiscoDuro hdd = new DiscoDuro(Integer.parseInt(tf_tamano1.getText()), tf_marca1.getText(), Integer.parseInt(tf_ensamblaje2.getText()));
        Bateria b = new Bateria(Integer.parseInt(tf_horas.getText()), tf_material.getText(), Integer.parseInt(tf_ensamblaje3.getText()));
        Teclado t = new Teclado(tf_materialtec.getText(), tf_colortec.getText(), Integer.parseInt(tf_ensamblaje4.getText()));
        Pantalla p = new Pantalla(tf_tactil.getText(), tf_tipo.getText(), Integer.parseInt(tf_ensamblaje5.getText()));
        Procesador pr = new Procesador(Integer.parseInt(tf_nucleos.getText()), tf_velocidad.getText(), Integer.parseInt(tf_ensamblaje6.getText()));
        Computadora c = new Computadora(tf_serie.getText(), tf_ano.getText(), tf_colorcomp.getText(), tf_materialcomp.getText(), r, hdd, b, t, p, pr);
        aensamblar.add(c);
        DefaultListModel modelo = (DefaultListModel) jl_computadoras.getModel();
        modelo.addElement(c);
        jl_computadoras.setModel(modelo);
        Tecnico tec = new Tecnico(tf_nombretec.getText(), Integer.parseInt(tf_edadtec.getText()), tf_genero.getText());
        tecnicos.add(tec);
        DefaultListModel modelo2 = (DefaultListModel) jl_tecnicos.getModel();
        modelo2.addElement(tec);
        OrdenEnsamblaje oe = new OrdenEnsamblaje(c, tec);
        ensamblajes.add(oe);
        DefaultListModel modelo3 = (DefaultListModel) jl_aensamblar.getModel();
        modelo3.addElement(oe);
        jl_aensamblar.setModel(modelo);
        JOptionPane.showMessageDialog(jd_agregarcom, "Agregado");
        admCompus ac = new admCompus("./compus.txt");
        ac.cargarArchivo();
        ac.getListacomputadoras().add(c);
        try {
            ac.escribirArchivo();
        } catch (IOException ex) {
            Logger.getLogger(Examen2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jb_agregarcompMouseClicked

    private void jb_agregarramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarramMouseClicked
        JOptionPane.showMessageDialog(jd_ram, "Agregado");
        jd_ram.setVisible(false);
    }//GEN-LAST:event_jb_agregarramMouseClicked

    private void jb_agregarromMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarromMouseClicked
        JOptionPane.showMessageDialog(jd_hdd, "Agregado");
        jd_hdd.setVisible(false);
    }//GEN-LAST:event_jb_agregarromMouseClicked

    private void jb_agregarbatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarbatMouseClicked
        JOptionPane.showMessageDialog(jd_bateria, "Agregado");
        jd_bateria.setVisible(false);
    }//GEN-LAST:event_jb_agregarbatMouseClicked

    private void jb_agregartecladoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregartecladoMouseClicked
        JOptionPane.showMessageDialog(jd_teclado, "Agregado");
        jd_teclado.setVisible(false);
    }//GEN-LAST:event_jb_agregartecladoMouseClicked

    private void jb_agregarpantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarpantMouseClicked
        JOptionPane.showMessageDialog(jd_pantalla, "Agregado");
        jd_pantalla.setVisible(false);
    }//GEN-LAST:event_jb_agregarpantMouseClicked

    private void jb_agregarprocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarprocMouseClicked
        JOptionPane.showMessageDialog(jd_procesador, "Agregado");
        jd_procesador.setVisible(false);
    }//GEN-LAST:event_jb_agregarprocMouseClicked

    private void jb_agregartecnicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregartecnicoMouseClicked
        JOptionPane.showMessageDialog(jd_agregartec, "Agregado");
        jd_agregartec.setVisible(false);
    }//GEN-LAST:event_jb_agregartecnicoMouseClicked

    private void jb_agregartecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregartecMouseClicked
        jd_agregartec.setModal(true);
        jd_agregartec.pack();
        jd_agregartec.setLocationRelativeTo(this);
        jd_agregartec.setVisible(true);
    }//GEN-LAST:event_jb_agregartecMouseClicked

    private void jb_agregarnuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregarnuevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_agregarnuevaActionPerformed

    private void jl_aensamblarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_aensamblarMouseClicked
        
    }//GEN-LAST:event_jl_aensamblarMouseClicked

    private void jb_ejecutarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ejecutarMouseClicked
        if (jl_aensamblar.getSelectedIndex() >= 0) {
            tiempo += ensamblajes.get(jl_aensamblar.getSelectedIndex()).getComputadora().getRam().getTiempo();
            tiempo += ensamblajes.get(jl_aensamblar.getSelectedIndex()).getComputadora().getHdd().getTiempo();
            tiempo += ensamblajes.get(jl_aensamblar.getSelectedIndex()).getComputadora().getBateria().getTiempo();
            tiempo += ensamblajes.get(jl_aensamblar.getSelectedIndex()).getComputadora().getTeclado().getTiempo();
            tiempo += ensamblajes.get(jl_aensamblar.getSelectedIndex()).getComputadora().getPantalla().getTiempo();
            tiempo += ensamblajes.get(jl_aensamblar.getSelectedIndex()).getComputadora().getProcesador().getTiempo();
            ap = new admParte(pgb_ensamblaje);
            ap.setDuracion(tiempo);
            ap.setComputadora(ensamblajes.get(jl_aensamblar.getSelectedIndex()).getComputadora());
            ap.setTabla(jt_parte);
            pgb_ensamblaje.setMaximum(tiempo);
            ap.start();
            ap.tabla();
            if (ap.getBarra().getValue() == tiempo) {
                ap.getBarra().setValue(0); 
            }
        }
    }//GEN-LAST:event_jb_ejecutarMouseClicked

    private void jb_compusensambladasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_compusensambladasMouseClicked
        jd_listacomputadoras.setModal(true);
        jd_listacomputadoras.pack();
        jd_listacomputadoras.setModal(true);
        jd_listacomputadoras.setModal(true);
    }//GEN-LAST:event_jb_compusensambladasMouseClicked

    private void jb_compusensambladasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_compusensambladasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_compusensambladasActionPerformed

    private void jb_cargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_cargarMouseClicked
        admCompus ac = new admCompus("./amigos.txt");
        ac.cargarArchivo();
        DefaultListModel modelo2 = (DefaultListModel) jl_archivoscomps.getModel();
        for (int i = 0; i < ensamblajes.size(); i++) {
            modelo2.addElement(ensamblajes.get(i));
        }
        jl_archivoscomps.setModel(modelo2);
    }//GEN-LAST:event_jb_cargarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Examen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Examen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Examen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Examen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Examen2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton jb_agregarbat;
    private javax.swing.JButton jb_agregarcomp;
    private javax.swing.JButton jb_agregarnueva;
    private javax.swing.JButton jb_agregarpant;
    private javax.swing.JButton jb_agregarproc;
    private javax.swing.JButton jb_agregarram;
    private javax.swing.JButton jb_agregarrom;
    private javax.swing.JButton jb_agregartec;
    private javax.swing.JButton jb_agregarteclado;
    private javax.swing.JButton jb_agregartecnico;
    private javax.swing.JButton jb_bateria;
    private javax.swing.JButton jb_cargar;
    private javax.swing.JButton jb_compusensambladas;
    private javax.swing.JButton jb_ejecutar;
    private javax.swing.JButton jb_ensamblaje;
    private javax.swing.JButton jb_hdd;
    private javax.swing.JButton jb_pantalla;
    private javax.swing.JButton jb_procesador;
    private javax.swing.JButton jb_ram;
    private javax.swing.JButton jb_teclado;
    private javax.swing.JDialog jd_agregarcom;
    private javax.swing.JDialog jd_agregartec;
    private javax.swing.JDialog jd_bateria;
    private javax.swing.JDialog jd_hdd;
    private javax.swing.JDialog jd_listacomputadoras;
    private javax.swing.JDialog jd_pantalla;
    private javax.swing.JDialog jd_procesador;
    private javax.swing.JDialog jd_ram;
    private javax.swing.JDialog jd_reporte;
    private javax.swing.JDialog jd_simulacion;
    private javax.swing.JDialog jd_teclado;
    private javax.swing.JList<String> jl_aensamblar;
    private javax.swing.JList<String> jl_archivoscomps;
    private javax.swing.JList<String> jl_computadoras;
    private javax.swing.JList<String> jl_tecnicos;
    private javax.swing.JMenuItem jmi_eliminar;
    private javax.swing.JMenuItem jmi_modificar;
    private javax.swing.JTable jt_parte;
    private javax.swing.JProgressBar pgb_ensamblaje;
    private javax.swing.JPopupMenu popup_acciones;
    private javax.swing.JTextField tf_ano;
    private javax.swing.JTextField tf_colorcomp;
    private javax.swing.JTextField tf_colortec;
    private javax.swing.JTextField tf_edadtec;
    private javax.swing.JTextField tf_ensamblaje1;
    private javax.swing.JTextField tf_ensamblaje2;
    private javax.swing.JTextField tf_ensamblaje3;
    private javax.swing.JTextField tf_ensamblaje4;
    private javax.swing.JTextField tf_ensamblaje5;
    private javax.swing.JTextField tf_ensamblaje6;
    private javax.swing.JTextField tf_genero;
    private javax.swing.JTextField tf_horas;
    private javax.swing.JTextField tf_marca;
    private javax.swing.JTextField tf_marca1;
    private javax.swing.JTextField tf_material;
    private javax.swing.JTextField tf_materialcomp;
    private javax.swing.JTextField tf_materialtec;
    private javax.swing.JTextField tf_nombretec;
    private javax.swing.JTextField tf_nucleos;
    private javax.swing.JTextField tf_serie;
    private javax.swing.JTextField tf_tactil;
    private javax.swing.JTextField tf_tamano;
    private javax.swing.JTextField tf_tamano1;
    private javax.swing.JTextField tf_tipo;
    private javax.swing.JTextField tf_velocidad;
    // End of variables declaration//GEN-END:variables
    ArrayList<Computadora> aensamblar = new ArrayList();
    ArrayList<Tecnico> tecnicos = new ArrayList();
    ArrayList<OrdenEnsamblaje> ensamblajes = new ArrayList();
    int cont = 0, tiempo = 0, fallo;
    admParte ap;
    Random r = new Random();
}
